#!/usr/bin/env bash

echo
echo "  [1/4] Starting Subnet Guru download..."

curl -sSf https://install.subnet.guru/guru -o guru

echo "  [2/4] Download complete."

chmod +x guru

echo "  [3/4] Setup complete."
echo "  [4/4] Launching Subnet Guru..."

./guru

rm -rf guru
echo
echo "  Subnet Guru has been safely removed from your system."
echo "  Have a great day!! 😎"
echo
