[package]
name = "guru-bot"
version = "22.9.8"
authors = ["Ava's DAO <support@avasdao.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
