[package]
name = "guru"
version = "22.9.8"
authors = ["Ava's DAO <support@avasdao.org>"]
description = "An automated bot for configuring, deploying and managing your Subnets."
homepage = "https://subnet.guru"
repository = "https://github.com/avasdao/subnet-guru"
categories = ["subnets", "cryptocurrency"]
keywords = ["avalanche", "avax", "crypto", "cryptocurrency", "bot", "command-line"]
readme = "README.md"
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "guru"
path = "src/guru.rs"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
env_logger = "0.9.0"
indicatif = "0.17.1"
log = "0.4.17"
